M48
; DRILL file {KiCad 9.0.2-9.0.2-0~ubuntu24.04.1} date 2025-07-11T12:15:57+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-11T12:15:57+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2-9.0.2-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X2.7012Y-4.4644
X2.9287Y-4.4644
M30
